language: java
sudo: false
script: mvn clean verify

deploy:
   provider: cloudfoundry
   username: jgsistem@gmail.com
   password: .Tr3vol17
   api: https://api.run.pivotal.io
   organization: JG17
   space: development