CREATE TABLE rol (
	id_rol BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
	detalle VARCHAR (60)  NOT NULL,
	islocked BOOLEAN NULL,
	PRIMARY KEY (id_rol)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;